# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b2adc0192f8094f8d211f843b9a88b5e388d8632a8a5109a4f239741daf863b56e84a596f4abbf15593a011902243d84eb33a80007a411db2e501a5a04ea92eb

test:
  secret_key_base: 47b7630adc6b340a9aec100c586c91cead4bf8f9dea83ae4dcc9b4373eb4826007eab57e512f546f0958725137971748e68d9edfcaeaf2669d51641a08b52462

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
